[pytest]
testpaths = tests

python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    unit: tests unitaires
    e2e: tests end-to-end via Selenium

addopts = -v --strict-markers
